version: "3"
services:
  db:
     container_name: db_server
     restart: always
     image: mysql/mysql-server:5.6
     environment:
       MYSQL_ROOT_PASSWORD: 'root'
     volumes:
      - "/opt/mysql_data:/var/lib/mysql"
     ports:
      - 3306:3306
  web:
      container_name: appserver
      restart: always
      image: nimmis/apache-php5
      links:
       - db
      volumes:
       - "/opt/app:/var/www/html"
      ports:
       - 8081:80
